"""..."""

from typing import Optional

from sqlmodel import Session, select

from dundie.models import Balance, Movement, Person, User
from dundie.settings import EMAIL_FROM
from dundie.utils.email import send_email


def add_person(session: Session, instance: Person):
    """Save person data to database."""
    """
    - If exists, update, else create
    - Set initial balance (managers = 100, others = 500)
    - Generate a password if user is new and send_email
    """
    existing = session.exec(
        select(Person).where(Person.email == instance.email)
    ).first()
    created = existing is None
    if created:
        session.add(instance)
        set_initial_balance(session, instance)
        password = set_initial_password(session, instance)
        # TODO: Usar sistema de filas (conteudo extra)
        send_email(
            EMAIL_FROM, instance.email, "Your dundie password", password
        )
        return instance, created
    else:
        existing.dept = instance.dept  # type: ignore
        existing.role = instance.role  # type: ignore
        existing.currency = instance.currency  # type: ignore
        session.add(existing)
        return instance, created


def set_initial_password(session: Session, instance: Person) -> str:
    """Generate and saves password."""
    user = User(person=instance)  # password generated by model
    session.add(user)
    return user.password


def set_initial_balance(session: Session, person: Person):
    """Add movement and set initial balance."""
    value = 100 if person.role == "Manager" else 500
    add_movement(session, person, value)


def add_movement(
    session: Session,
    person: Person,
    value: int,
    actor: Optional[str] = "system",
):
    """Add movement to user account.

    Example::

        add_movement(db, Person(...), 100, "me")

    """
    movement = Movement(person=person, value=value, actor=actor)
    session.add(movement)

    movements = session.exec(select(Movement).where(Movement.person == person))

    total = sum([mov.value for mov in movements])

    existing_balance = session.exec(
        select(Balance).where(Balance.person == person)
    ).first()
    if existing_balance:
        existing_balance.value = total
        session.add(existing_balance)
    else:
        session.add(Balance(person=person, value=total))
