"""initial

Revision ID: 4594b7879fd2
Revises: 
Create Date: 2022-04-12 16:11:53.157665

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '4594b7879fd2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'blalala')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('blalala', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
