"""Initial.

Revision ID: bbd9c1f900ee
Revises:
Create Date: 2022-09-09 16:14:50.344839

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'bbd9c1f900ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('person', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('person', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
